# Generated by Django 3.2.12 on 2022-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email of the user')),
                ('password', models.CharField(max_length=100, verbose_name='Password of the user')),
                ('usertype', models.CharField(max_length=10, verbose_name='Type of the user')),
                ('lastlogin', models.DateTimeField(max_length=10, verbose_name='Type of the user')),
            ],
        ),
    ]
