# Generated by Django 3.2.12 on 2022-03-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the device')),
                ('usertype', models.CharField(max_length=10, verbose_name='Type of the user')),
                ('lastlogin', models.DateTimeField(max_length=10, verbose_name='Type of the user')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the media')),
                ('path', models.CharField(max_length=255, verbose_name='Path to the media')),
                ('isvideo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the ticket')),
                ('issueType', models.CharField(max_length=100, verbose_name='Type of the issue')),
                ('description', models.CharField(max_length=10000, verbose_name='Description of the issue')),
                ('stage', models.IntegerField(verbose_name='Stage of the issue')),
                ('complete', models.BooleanField()),
                ('solutionText', models.CharField(max_length=10000, null=True, verbose_name='Text of the solution')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to='techsupport.user')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='techsupport.user')),
                ('deviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupport.devices')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='techsupport.media')),
                ('solutionVideo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutionVideo', to='techsupport.media')),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupport.media'),
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(max_length=10)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='techsupport.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='techsupport.user')),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupport.tickets')),
            ],
        ),
    ]
