# Generated by Django 4.0.3 on 2022-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0002_auto_20220315_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email of the user'),
        ),
    ]
