# Generated by Django 3.2.12 on 2022-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='lastlogin',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(max_length=10, verbose_name='Last login date'),
        ),
    ]
