# Generated by Django 3.2.12 on 2022-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0009_alter_media_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Name of the media'),
        ),
    ]
